{% set name = "tsv-utils" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/eBay/tsv-utils/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 07c8a62962f9bb624f402281ccb3c571509d4bc48f8fdc5a1d056775bc764e9a

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ldc  # [not (osx and arm64)]

test:
  commands:
    - "csv2tsv -V"
    - "tsv-filter -h"

about:
  home: https://github.com/eBay/tsv-utils
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: "eBay's TSV Utilities"
  description: |
    Command line tools for large, tabular data files. 
    Filtering, statistics, sampling, joins and more.
  doc_url: https://ebay.github.io/tsv-utils/
  dev_url: https://github.com/eBay/tsv-utils#obtaining-and-installation

extra:
  recipe-maintainers:
    - corneliusroemer
