azure:
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
provider:
  linux_aarch64: default
test: native_and_emulated
